# -----------
# API Server
# -----------

### Env
@baseUrl={{$dotenv API_URL}}

### Default
GET {{baseUrl}}/

### Trigger
POST {{baseUrl}}/q/trigger
Content-Type: application/json

{
    "message": "Hello World"
}